// components/menu/menu.data.ts
// ── Static data for development — swap with API later ──

import { Meal } from "./menu.types";

export const STATIC_MEALS: Meal[] = [

  // ── STARTERS ──
  {
    _id: "1",
    name: "Salmon Tartare",
    description: "Fresh Atlantic salmon, avocado cream, capers, lemon zest and toasted brioche.",
    price: 1800,
    category: "Starters",
    image: "/images/1.jpg",
    tags: ["Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
  {
    _id: "2",
    name: "Grilled Octopus",
    description: "Tender octopus, smoked paprika oil, pickled vegetables and fresh herbs.",
    price: 2200,
    category: "Starters",
    image: "/images/2.jpg",
    tags: ["Spicy", "Gluten-Free"],
    isVisible: true,
    isPromotion: true,
    promotionPrice: 1700,
  },
  {
    _id: "3",
    name: "Vegetable Spring Rolls",
    description: "Crispy rolls filled with seasonal vegetables, glass noodles and sweet chili sauce.",
    price: 1200,
    category: "Starters",
    image: "/images/3.jpg",
    tags: ["Vegan"],
    isVisible: true,
    isPromotion: false,
  },

  // ── MAIN COURSE ──
  {
    _id: "4",
    name: "Grilled Lamb Chops",
    description: "Marinated lamb chops, roasted garlic mash, mint jus and seasonal vegetables.",
    price: 3800,
    category: "Main Course",
    image: "/images/4.jpg",
    tags: ["Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
  {
    _id: "5",
    name: "Chicken Tagine",
    description: "Slow-cooked chicken with preserved lemons, olives, saffron and couscous.",
    price: 2900,
    category: "Main Course",
    image: "/images/5.jpg",
    tags: ["Spicy"],
    isVisible: true,
    isPromotion: true,
    promotionPrice: 2300,
  },
  {
    _id: "6",
    name: "Mushroom Risotto",
    description: "Arborio rice, wild mushrooms, aged parmesan, truffle oil and fresh thyme.",
    price: 2400,
    category: "Main Course",
    image: "/images/6.jpg",
    tags: ["Vegan", "Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },

  // ── SEAFOOD ──
  {
    _id: "7",
    name: "Grilled Sea Bass",
    description: "Whole sea bass, lemon butter sauce, steamed vegetables and saffron rice.",
    price: 4200,
    category: "Seafood",
    image: "/images/7.jpg",
    tags: ["Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
  {
    _id: "8",
    name: "King Prawns",
    description: "Jumbo prawns, garlic butter, white wine, cherry tomatoes and crusty bread.",
    price: 4800,
    category: "Seafood",
    image: "/images/8.jpg",
    tags: ["Spicy", "Gluten-Free"],
    isVisible: true,
    isPromotion: true,
    promotionPrice: 3900,
  },
  {
    _id: "9",
    name: "Lobster Thermidor",
    description: "Half lobster, cream sauce, gruyère gratin, served with seasonal greens.",
    price: 6500,
    category: "Seafood",
    image: "/images/9.jpg",
    tags: [],
    isVisible: true,
    isPromotion: false,
  },

  // ── DESSERTS ──
  {
    _id: "10",
    name: "Crème Brûlée",
    description: "Classic vanilla custard with a perfectly caramelized sugar crust.",
    price: 900,
    category: "Desserts",
    image: "/images/10.jpg",
    tags: ["Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
  {
    _id: "11",
    name: "Chocolate Fondant",
    description: "Warm dark chocolate cake with a molten center, vanilla ice cream and praline.",
    price: 1100,
    category: "Desserts",
    image: "/images/11.jpg",
    tags: [],
    isVisible: true,
    isPromotion: true,
    promotionPrice: 850,
  },
  {
    _id: "12",
    name: "Fruit Sorbet",
    description: "Three scoops of seasonal fruit sorbet — mango, raspberry and passion fruit.",
    price: 800,
    category: "Desserts",
    image: "/images/12.jpg",
    tags: ["Vegan", "Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },

  // ── DRINKS ──
  {
    _id: "13",
    name: "Fresh Mint Lemonade",
    description: "House-squeezed lemon, fresh mint, cane sugar and sparkling water.",
    price: 600,
    category: "Drinks",
    image: "/images/13.jpg",
    tags: ["Vegan", "Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
  {
    _id: "14",
    name: "Mango Passion Smoothie",
    description: "Fresh mango, passion fruit, coconut milk and a hint of ginger.",
    price: 750,
    category: "Drinks",
    image: "/images/14.jpg",
    tags: ["Vegan", "Gluten-Free"],
    isVisible: true,
    isPromotion: true,
    promotionPrice: 550,
  },
  {
    _id: "15",
    name: "Moroccan Mint Tea",
    description: "Traditional green tea with fresh mint leaves and hand-rolled sugar cones.",
    price: 400,
    category: "Drinks",
    image: "/images/15.jpg",
    tags: ["Vegan", "Gluten-Free"],
    isVisible: true,
    isPromotion: false,
  },
];